apiVersion: v1
kind: Service
metadata:
  name: bsf-svc
  labels:
    epc-mode: bsf
spec:
  selector:
    epc-mode: bsf
  ports:
    - protocol: TCP
      port: 80   
      targetPort: 80
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bsf-deployment
  labels:
    epc-mode: bsf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: bsf
  template:
    metadata:
      labels:
        epc-mode: bsf
    spec:
      serviceAccountName: {{ .Release.Name }}-k8s-wait-for
      initContainers:     
      - name: wait-for-scp
        image: "{{ .Values.k8swait.repository }}:{{ .Values.k8swait.tag }}"
        imagePullPolicy: {{ .Values.k8swait.pullPolicy }}
        securityContext:
            readOnlyRootFilesystem: true
        args:
          - "pod"
          - "-lepc-mode=scp"
      containers:
        - name: bsf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
          - open5gs-bsfd -c /open5gs/config-map/bsf.yaml;
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
          - name: {{ .Release.Name }}-bsf-config
            mountPath: /open5gs/config-map/bsf.yaml
            subPath: "bsf.yaml"  
          - name: logs
            mountPath: /var/log/open5gs 
      volumes:
        - name: {{ .Release.Name }}-bsf-config
          configMap:
            name: {{ .Release.Name }}-bsf-config
        - name: logs
          emptyDir: {}